apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    name: discovery-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: discovery-service
  type: LoadBalancer